name: Build fedora rpm package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ucode/

      - name: Install dependencies
        run: |
          sudo dnf -y install fedora-packager fedora-review

      - name: Get Fedora version
        run: echo "FEDORA_VERSION_SHORT=f$(grep VERSION_ID /etc/os-release | cut -d'=' -f2)" >> $GITHUB_ENV

      # - name: Render .spec file
      #   id: render_spec_file
      #   uses: chuhlomin/render-template@v1
      #   with:
      #     template: ./.github/workflows/ucode.template.spec
      #     vars: |
      #       version: ${{ env.GITVERSION }}

      - name: Render version in .spec file
        run: |
          echo "Name:           ucode" > ucode.spec
          echo "Version:        ${GITVERSION#v}" >> ucode.spec

      - name: Save rest of .spec file
        run: |
          echo 'Release:        %autorelease' >> ucode.spec
          echo 'Summary:        JavaScript-like language with optional templating' >> ucode.spec
          echo ' ' >> ucode.spec
          echo 'License:        ISC' >> ucode.spec
          echo 'URL:            https://ucode.mein.io/' >> ucode.spec
          echo 'Source:         https://github.com/jow-/ucode/archive/refs/tags/v%{version}.tar.gz' >> ucode.spec
          echo ' ' >> ucode.spec
          echo 'BuildRequires:  gcc' >> ucode.spec
          echo 'BuildRequires:  make' >> ucode.spec
          echo 'BuildRequires:  cmake' >> ucode.spec
          echo 'BuildRequires:  json-c-devel' >> ucode.spec
          echo 'BuildRequires:  texinfo' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%description' >> ucode.spec
          echo 'The ucode language is a small, general-purpose scripting language that' >> ucode.spec
          echo 'resembles ECMAScript syntax. It can be used as a standalone interpreter or' >> ucode.spec
          echo 'embedded into host applications. Ucode supports template mode with control flow' >> ucode.spec
          echo 'and expression logic statements embedded in Jinja-like markup blocks.' >> ucode.spec
          echo ' ' >> ucode.spec
          echo 'Initially intended as a template processor, ucode evolved into a versatile' >> ucode.spec
          echo 'scripting language for various system scripting tasks. Its design goals include' >> ucode.spec
          echo 'easy integration with C applications, efficient handling of JSON data and' >> ucode.spec
          echo 'complex data structures, support for OpenWrt's ubus message bus system, and a' >> ucode.spec
          echo 'comprehensive set of built-in functions inspired by Perl 5.' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%package    -n libucode' >> ucode.spec
          echo 'Summary:    Shared library files for ucode' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%description -n libucode' >> ucode.spec
          echo 'This package contains the compiled shared libraries for ucode.' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%package    -n libucode-devel' >> ucode.spec
          echo 'Summary:    Development files for ucode' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%description -n libucode-devel' >> ucode.spec
          echo 'This package contains libraries and header files for developing applications' >> ucode.spec
          echo 'that use ucode.' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%prep' >> ucode.spec
          echo '%autosetup' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%build' >> ucode.spec
          echo '%cmake -DUBUS_SUPPORT=OFF \' >> ucode.spec
          echo '    -DUCI_SUPPORT=OFF \' >> ucode.spec
          echo '    -DULOOP_SUPPORT=OFF \' >> ucode.spec
          echo '    -DCMAKE_BUILD_TYPE=Release' >> ucode.spec
          echo '%cmake_build' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%install' >> ucode.spec
          echo '%cmake_install' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%files' >> ucode.spec
          echo '%{_bindir}/ucc' >> ucode.spec
          echo '%{_bindir}/ucode' >> ucode.spec
          echo '%{_bindir}/utpl' >> ucode.spec
          echo '%doc README.md' >> ucode.spec
          echo '%license LICENSE' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%files  -n libucode' >> ucode.spec
          echo '%{_prefix}/lib/libucode.so' >> ucode.spec
          echo '%{_prefix}/lib/libucode.so.0' >> ucode.spec
          echo '%{_prefix}/lib/ucode/debug.so' >> ucode.spec
          echo '%{_prefix}/lib/ucode/fs.so' >> ucode.spec
          echo '%{_prefix}/lib/ucode/log.so' >> ucode.spec
          echo '%{_prefix}/lib/ucode/math.so' >> ucode.spec
          echo '%{_prefix}/lib/ucode/resolv.so' >> ucode.spec
          echo '%{_prefix}/lib/ucode/struct.so' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%files  -n libucode-devel' >> ucode.spec
          echo '%{_includedir}/ucode/chunk.h' >> ucode.spec
          echo '%{_includedir}/ucode/compiler.h' >> ucode.spec
          echo '%{_includedir}/ucode/lexer.h' >> ucode.spec
          echo '%{_includedir}/ucode/lib.h' >> ucode.spec
          echo '%{_includedir}/ucode/module.h' >> ucode.spec
          echo '%{_includedir}/ucode/platform.h' >> ucode.spec
          echo '%{_includedir}/ucode/program.h' >> ucode.spec
          echo '%{_includedir}/ucode/source.h' >> ucode.spec
          echo '%{_includedir}/ucode/types.h' >> ucode.spec
          echo '%{_includedir}/ucode/util.h' >> ucode.spec
          echo '%{_includedir}/ucode/vallist.h' >> ucode.spec
          echo '%{_includedir}/ucode/vm.h' >> ucode.spec
          echo ' ' >> ucode.spec
          echo '%changelog' >> ucode.spec
          echo '%autochangelog' >> ucode.spec

      - name: Build package
        run: |
          spectool -g ucode.spec
          fedpkg --release ${{ env.FEDORA_VERSION_SHORT }} mockbuild

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: rpm
          path: '*ucode*.rpm'
